### ISSUE TITLE
umask in ServicebrokerServer.cpp

### ISSUE THREAD

**Issue by ptka** [DSIHarman/DSI#1]
On Ubuntu 11.04 the following compile error occurs:

cd /home/piet/Projects/Harman/DSI/build/debug/src/servicebroker && /usr/bin/c++    -g -I/home/piet/Projects/Harman/DSI/include -I/home/piet/Projects/Harman/DSI/src/servicebroker/. -I/home/piet/Projects/Harman/DSI/src/servicebroker/../common    -Wall -W -o CMakeFiles/servicebroker.dir/ServicebrokerServer.cpp.o -c /home/piet/Projects/Harman/DSI/src/servicebroker/ServicebrokerServer.cpp
/home/piet/Projects/Harman/DSI/src/servicebroker/ServicebrokerServer.cpp: In member function ‘bool ServicebrokerServer::init(const char_, MasterAdapter_, unsigned int, const char*)’:
/home/piet/Projects/Harman/DSI/src/servicebroker/ServicebrokerServer.cpp:618:29: error: ‘umask’ was not declared in this scope

Adding the following include, fixes the problem:
# include <sys/stat.h> // umask

**Comment by ptka** [comment]
#include <sys/stat.h> // umask

**Comment by martinhaefner** [comment]
Certainly a bug. We will fix it.

**Comment by filorom** [comment]
Closed with commit 847b6ab275dccec73cf3383aeaf8dda3d5b4b860
