### ISSUE TITLE
missing /var/run/servicebroker

### ISSUE THREAD

**Issue by ptka** [DSIHarman/DSI#2]
Calling ./update.sh test should start the included tests.

But directory /var/run/servicebroker is missing by default, which is required for the servicebroker.

Creating the directory manually with 0777, fixes the problem, but 0777 in /var/run is most likely not a good idea.

**Comment by martinhaefner** [comment]
After calling make install as root user an upstart script will be added so after a reboot the mountpoint is available. This is obviously not documented. But for testing purposes we should move the mountpoint of the servicebroker to a /tmp or a local directory. We should add an appropriate commandline switch or (maybe better) environment variable which is is set for the testing.

**Comment by martinhaefner** [comment]
Done using new environment variable DSI_SB_ROOT in test drivers
